[tool.poetry]
name = "numx-subnet"
version = "0.1.0"
description = ""
authors = ["NUMENEX"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
configparser = "^7.0.0"
communex = "^0.1.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
